site_name: Go Project Template
site_url: https://swade1987.github.io/go-project-template
repo_name: swade1987/go-project-template
repo_url: https://github.com/swade1987/go-project-template
edit_uri: ""

site_dir: public

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.sections

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
